### ISSUE TITLE
property 'error' of undefined

### ISSUE THREAD

**Issue by steeply** [dutu/poloniex-api-node#12]
Cannot read property 'error' of undefined

```
/home/shura/bots/app-trader-master/node_modules/poloniex-api-node/lib/poloniex.js:63
err =  new Error(`Poloniex error ${response.statusCode}: ${response.body.error || response.body}`);
                                                                         ^
at Request._callback (/home/shura/bots/btce-app-trader-master/node_modules/poloniex-api-node/lib/poloniex.js:63:93)
at Request.self.callback (/home/shura/bots/app-trader-master/node_modules/request/request.js:188:22)

```

**Comment by dutu** [comment]
fixed in version 1.1.0
