### ISSUE TITLE
Getting issue regarding strict mode

### ISSUE THREAD

**Issue by Miladinho** [dutu/poloniex-api-node#27]
/node_modules/poloniex-api-node/lib/poloniex.js:48
class Poloniex extends EventEmitter {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by Miladinho** [comment]
Node was out of date. Not an issue. Thanks for patience
