### ISSUE TITLE
Poloniex error 422: . Invalid currencyPair parameter

### ISSUE THREAD

**Issue by bennytjia** [dutu/poloniex-api-node#51]
I received the error after making a buy REST call. All public API call worked just fine and no error related to API key and secret. I've also tried creating new API key and secret.

The error happened after I make a test call using the code below:
```javascript
_poloniex.buy({
    currencyPair: 'BTC_BCH',
   	rate: 0.058,
    amount: 1,
 }).then(msg => console.log(msg.body))
.catch(err => console.log(err))
```
Complete error messages below:
Error: Poloniex error 422: . Invalid currencyPair parameter.
    at Request._callback (/Users/user_a/poloniex_project/node_modules/poloniex-api-node/lib/poloniex.js:161:18)
    at Request.self.callback (/Users/user_a/poloniex_project/node_modules/request/request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/Users/user_a/poloniex_project/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/Users/user_a/poloniex_project/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)

**Comment by dutu** [comment]
need to pass multiple parameters, rather than one single JSON object.
