### ISSUE TITLE
Error websocket: closing the server after hours on

### ISSUE THREAD

**Issue by PerduGames** [dutu/poloniex-api-node#64]
I am using the module in version 1.8.1(downloaded by npm install --save poloniex-api-node) and writing a code as below:

```
'use strict';
const Poloniex = require('poloniex-api-node');
let poloniex = new Poloniex();
var btc_ltc = null;

poloniex.on('open', () => {
    console.log(`WebSocket connection has be opened.`);
    poloniex.subscribe('ticker');
    poloniex.on('message', (channelName, data) => {

        if (channelName === 'ticker') {
            if (data['currencyPair'] === 'BTC_LTC') {
                btc_ltc = {
                    "currencyPair": data['currencyPair'],
                    "last": data['last'],
                    "lowestAsk": data['lowestAsk'],
                    "highestBid": data['highestBid'],
                    "percentChange": data['percentChange'],
                    "baseVolume": data['baseVolume'],
                    "quoteVolume": data['quoteVolume'],
                    "isFrozen": data['isFrozen'],
                    "24hrHigh": data['24hrHigh'],
                    "24hrLow": data['24hrLow']
                }
            }
        }
    });

});
```

The problem is that it works perfectly for a few hours on, but nothing happens to the server close and issue this error below:

```
Example app listening on port 3000!
WebSocket connection has be opened.
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: read ETIMEDOUT
    at TLSWrap.onread (net.js:599:25)
Emitted 'error' event at:
    at WebSocket.ws.onerror.args (/home/mycomputer/robotpoloniex/server/node_modules/poloniex-api-node/lib/poloniex.js:745:20)
    at WebSocket.onError (/home/mycomputer/robotpoloniex/server/node_modules/ws/lib/EventTarget.js:109:16)
    at WebSocket.emit (events.js:180:13)
    at WebSocket.finalize (/home/mycomputer/robotpoloniex/server/node_modules/ws/lib/WebSocket.js:182:41)
    at TLSSocket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
```

**Comment by dutu** [comment]
It looks that there is a timeout error. To handle it correctly and avoid the error to be thrown, you should also listen on the `error`event 
```js
poloniex.on('error', (error) => {
  console.log(`An error has occurred: ${JSON.stringify(error)}`);
});
```

**Comment by PerduGames** [comment]
But why does this error happen?

**Comment by dutu** [comment]
I'm not sure why the connection timeout happens , but you can handle the event so that it doesn't crash your application
