### ISSUE TITLE
Error processing

### ISSUE THREAD

**Issue by steeply** [dutu/poloniex-api-node#7]
1. Why show the entire stack of errors? These are not fatal errors, but simply a message!
2. Why did not you start using Promise?

```
Error: Not enough BTS.
    at Request._callback (/Applications/MAMP/htdocs/btc-e/node_modules/poloniex-api-node/lib/poloniex.js:69:27)
    at Request.self.callback (/Applications/MAMP/htdocs/btc-e/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/Applications/MAMP/htdocs/btc-e/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/Applications/MAMP/htdocs/btc-e/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```

**Comment by dutu** [comment]
1. An error is passed as first argument to the callback function, as an `Error` object.
[Node.js Errors](https://nodejs.org/api/errors.html)
[What are the error conventions?](https://docs.nodejitsu.com/articles/errors/what-are-the-error-conventions/)
[Understanding Error-First Callbacks](http://fredkschott.com/post/2014/03/understanding-error-first-callbacks-in-node-js/)
You should display `error.message` if `error !== null`

2. this library doesn't use promise, but just callbacks. I may add promise in one of the next versions
