### ISSUE TITLE
Websocket permission error

### ISSUE THREAD

**Issue by qadirp** [dutu/poloniex-api-node#85]
I added these lines in my app.js

```let poloniex = new Poloniex(keysObject['apikey'], keysObject['apisecret']); // values are coming I checked after logging
    poloniex.openWebSocket();
    poloniex.subscribe('accountNotifications');
    poloniex.on('message', (channelName, data) => {
        if (channelName === 'accountNotifications') {
            console.log(`account notifications update: ${JSON.stringify(data)}`);
        }
    })
```

and it is giving me errors below

```events.js:302
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Permission denied.')
    at Poloniex.emit (events.js:300:17)
    at WebSocket.ws.onmessage (/var/www/html/nodepoloniex/node_modules/poloniex-api-node/lib/poloniex.js:624:25)
```

**Comment by dutu** [comment]
Please use version >=3.0.0
